language: node_js
node_js:
  - "13.7.0"
services:
  - docker
before_install:
  - docker build -t rozdolsky33/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rozdolsky33/react-test npm test -- --coverage
after_success:
  - docker build -t rozdolsky33/multi-client ./client
  - docker build -t rozdolsky33/multi-nginx ./ngnix
  - docker build -t rozdolsky33/multi-service ./server
  - docker build -t rozdolsky33/multi-worker ./worker
  #Pushe images to the dockerHub
  # - login the docker with one command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #retrive docker pass from env | input of pass with a docker id expect to recive pass over stdin
  #Pushe images to  dockerHub
  - docker push rozdolsky33/multi-client
  - docker push rozdolsky33/multi-worker
  - docker push rozdolsky33/multi-nginx
  - docker push rozdolsky33/multi-service
    #no images on  dockerHub
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: MultiDocker-env
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-651261648885
  bucker_patch: docker multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secured: $AWS_SECRET_KEY
